# Generated by Django 3.2.9 on 2022-02-28 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1024)),
                ('status', models.CharField(default='A', max_length=3)),
                ('Instance_type', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=50)),
                ('server_name', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('description', models.CharField(max_length=1024)),
                ('role', models.CharField(max_length=50)),
                ('instance_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.instance')),
            ],
        ),
    ]
