# Generated by Django 4.0.1 on 2022-02-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji_quiz', '0003_alter_kanji_options_kanji_meaning'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portuguese',
            options={'verbose_name_plural': 'Portuguese'},
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='meaning',
        ),
        migrations.RemoveField(
            model_name='portuguese',
            name='translation',
        ),
        migrations.AddField(
            model_name='portuguese',
            name='meaning',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
