# Generated by Django 4.0.1 on 2022-02-03 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji_quiz', '0005_alter_kanji_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='level',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
