# Generated by Django 3.2.9 on 2022-03-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji_quiz', '0007_auto_20220312_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='meaning',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
