# Generated by Django 3.2.9 on 2022-03-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji_quiz', '0008_alter_kanji_meaning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='character',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Portuguese',
        ),
    ]
