# Generated by Django 4.0.1 on 2022-02-07 15:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Job requested', max_length=50)),
                ('application', models.CharField(max_length=50)),
                ('application_version', models.CharField(max_length=50)),
                ('start_datetime', models.DateTimeField(default=datetime.datetime(2022, 2, 7, 15, 32, 50, 178623))),
                ('end_datetime', models.DateTimeField()),
                ('description', models.CharField(default='pending', max_length=50)),
                ('instance_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.instance')),
                ('server_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.server')),
            ],
        ),
    ]
