# Generated by Django 4.0.1 on 2022-02-09 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_alter_runtime_start_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runtime',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 9, 20, 28, 50, 260333)),
        ),
    ]
