# Generated by Django 3.2.9 on 2022-03-01 11:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20220301_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtime',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.jobs'),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 1, 11, 31, 51, 412924), null=True),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 1, 11, 31, 51, 412924), null=True),
        ),
    ]
