# Generated by Django 3.2.9 on 2022-02-17 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_alter_runtime_start_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runtime',
            name='application',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='application_version',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='description',
            field=models.CharField(default='pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 17, 11, 42, 43, 279574), null=True),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='status',
            field=models.CharField(default='Job requested', max_length=50, null=True),
        ),
    ]
