# Generated by Django 3.2.9 on 2022-02-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ipm_appversions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_version', models.CharField(max_length=50, unique=True)),
                ('app_version_hier', models.CharField(max_length=25, null=True, unique=True)),
                ('description', models.CharField(max_length=1024)),
                ('status', models.CharField(default='A', max_length=3)),
                ('Rep_Status', models.CharField(choices=[('d', 'Draft'), ('p', 'Productionised'), ('w', 'Withdrawn')], max_length=1, null=b'I01\n')),
            ],
            options={
                'verbose_name_plural': 'iPM Application Versions',
            },
        ),
        migrations.CreateModel(
            name='lor_appversions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_version', models.CharField(max_length=50, unique=True)),
                ('app_version_hier', models.CharField(max_length=25, null=True, unique=True)),
                ('status', models.CharField(default='A', max_length=3)),
                ('description', models.CharField(max_length=1024)),
                ('Rep_Status', models.CharField(choices=[('d', 'Draft'), ('p', 'Productionised'), ('w', 'Withdrawn')], max_length=1, null=b'I01\n')),
            ],
            options={
                'verbose_name_plural': 'Lorenzo Application Versions',
            },
        ),
    ]
