# Generated by Django 3.2.9 on 2022-02-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20220217_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipm_appversions',
            name='Rep_Status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Productionised'), ('w', 'Withdrawn')], max_length=1, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='lor_appversions',
            name='Rep_Status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Productionised'), ('w', 'Withdrawn')], max_length=1, null=b'I01\n'),
        ),
    ]
