# Generated by Django 4.0.1 on 2022-02-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ipm_appversions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_version', models.CharField(max_length=50, unique=True)),
                ('app_version_hier', models.CharField(max_length=25, null=True, unique=True)),
                ('description', models.CharField(max_length=1024)),
                ('status', models.CharField(default='A', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='lor_appversions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_version', models.CharField(max_length=50, unique=True)),
                ('app_version_hier', models.CharField(max_length=25, null=True, unique=True)),
                ('status', models.CharField(default='A', max_length=3)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
    ]
