# Generated by Django 4.0.1 on 2022-02-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipm_appversions',
            options={'verbose_name_plural': 'iPM Application Versions'},
        ),
        migrations.AlterModelOptions(
            name='lor_appversions',
            options={'verbose_name_plural': 'Lorenzo Application Versions'},
        ),
    ]
