# Generated by Django 3.2.9 on 2022-02-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_lor_appversions_rep_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipm_appversions',
            name='Rep_Status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], max_length=1, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
