# Generated by Django 3.2.9 on 2022-02-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_ipm_appversions_rep_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipm_appversions',
            name='Rep_Status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Productionised'), ('w', 'Withdrawn'), ('r', 'Retired')], max_length=1, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='lor_appversions',
            name='Rep_Status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Productionised'), ('w', 'Withdrawn'), ('r', 'Retired')], max_length=1, null=b'I01\n'),
        ),
    ]
