# Generated by Django 4.0.1 on 2022-02-10 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_runtime_start_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runtime',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 11, 31, 17, 359071)),
        ),
    ]
