# Generated by Django 3.2.9 on 2022-03-03 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_auto_20220303_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtime',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 3, 16, 30, 51, 846260), null=True),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 3, 16, 30, 51, 846260), null=True),
        ),
    ]
